<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="Mobirise v5.6.5, mobirise.com">
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:image:src" content="">
    <meta property="og:image" content="">
    <meta name="twitter:title" content="Event`s List">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="shortcut icon" href="https://avatars.mds.yandex.net/get-images-cbir/1780765/YsrctO5AJ50pc5CFxhgIJw546/ocr" type="image/x-icon">
    <meta name="description" content="">


    <title>Event`s List</title>
    <link rel="stylesheet" href="/templates/assets/web/assets/mobirise-icons2/mobirise2.css">
    <link rel="stylesheet" href="/templates/assets/web/assets/mobirise-icons/mobirise-icons.css">
    <link rel="stylesheet" href="/templates/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/templates/assets/bootstrap/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="/templates/assets/bootstrap/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="/templates/assets/dropdown/css/style.css">
    <link rel="stylesheet" href="/templates/assets/socicon/css/styles.css">
    <link rel="stylesheet" href="/templates/assets/theme/css/style.css">
    <link rel="preload"
          href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"
          as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap">
    </noscript>
    <link rel="preload" as="style" href="/templates/assets/mobirise/css/mbr-additional.css">
    <link rel="stylesheet" href="/templates/assets/mobirise/css/mbr-additional.css" type="text/css">


</head>
<body>

<section data-bs-version="5.1" class="menu cid-s48OLK6784" once="menu" id="menu1-k">

    <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
        <div class="container-fluid">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="https://mobiri.se">
                        <img src="https://avatars.mds.yandex.net/get-images-cbir/1780765/YsrctO5AJ50pc5CFxhgIJw546/ocr" alt="error"
                             style="height: 3.9rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-black display-7"
                                                     href="https://mobiri.se">TatCenter</a></span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse"
                    data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true">
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4"
                                            href="/profile/me">Профиль</a></li>
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4"
                                            href="https://translate.tatar">Сервислар</a></li>
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4"
                                            href="/events">Чаралар</a></li>
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4"
                                            href="https://selet.biz/tat/">Мәдәният</a></li>
                </ul>
            </div>
        </div>
    </nav>

</section>

<section data-bs-version="5.1" class="content15 cid-t3bcE7d5du" id="content15-w">


    <div class="container">
        <div class="row justify-content-center">
            <div class="card col-md-12 col-lg-12">
                <div class="card-wrapper">
                    <div class="card-box align-left">
                        <h4 class="card-title mbr-fonts-style mbr-white mb-3 display-5"><strong>Барлык булган
                                чара</strong></h4>
                        <p class="mbr-text mbr-fonts-style display-7">Биредә алар белән танышырга була</p>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section data-bs-version="5.1" class="features1 cid-t3bgxVegTp" id="features2-10">


    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-6 col-lg-3">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <a href="/events/aralashu"><span
                                    class="mbr-iconfont mobi-mbri-users mobi-mbri"></span></a>
                        <h4 class="card-title align-center mbr-black mbr-fonts-style display-7"><strong>Аралашу</strong>
                        </h4>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <a href="/events/mirakh"><span
                                    class="mbr-iconfont mobi-mbri-cloud mobi-mbri"></span></a>
                        <h4 class="card-title align-center mbr-black mbr-fonts-style display-7">
                            <strong>Иҗат</strong></h4>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <a href="/events/intellectual"><span
                                    class="mbr-iconfont mobi-mbri-idea mobi-mbri"></span></a>
                        <h4 class="card-title align-center mbr-black mbr-fonts-style display-7"><strong>Интеллектуаль
                                чаралар</strong></h4>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <a href="/events/kamal"><span
                                    class="mbr-iconfont mbri-camera"></span></a>
                        <h4 class="card-title align-center mbr-black mbr-fonts-style display-7">
                            <strong>Постановкалар</strong></h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section data-bs-version="5.1" class="features15 cid-t3bba4G71j" id="features16-q">


    <div class="container">
        <div class="content-wrapper">
            <div class="row align-items-center">
                <div class="col-12 col-lg">
                    <div class="text-wrapper">
                        <h6 class="card-title mbr-fonts-style display-2"><strong>Tatar.Бу Хакатон</strong></h6>
                        <p class="mbr-text mbr-fonts-style mb-4 display-4">МЦ «Сэлэт»</p>
                        <div class="mbr-section-btn mt-3"><a class="btn btn-warning display-4"
                                                             href="https://mobiri.se/AnyLink1"><span
                                        class="mobi-mbri mobi-mbri-like mbr-iconfont mbr-iconfont-btn"></span>Ошый</a>
                            <a
                                    class="btn btn-warning display-4" href="https://mobiri.se/AnyLink1">3</a> <a
                                    class="btn btn-warning display-4" href="/events/hackathon">Күчәргә</a>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-4">
                    <div class="image-wrapper">
                        <img src="https://static.tildacdn.com/tild3362-3666-4233-b936-653032363764/tatar.png"
                             alt="error">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section data-bs-version="5.1" class="features15 cid-t3bcrbjfIx" id="features16-u">


    <div class="container">
        <div class="content-wrapper">
            <div class="row align-items-center">
                <div class="col-12 col-lg">
                    <div class="text-wrapper">
                        <h6 class="card-title mbr-fonts-style display-2"><strong>Конкурс грантов на реализацию
                                Стартапов</strong></h6>
                        <p class="mbr-text mbr-fonts-style mb-4 display-4">Правительство РФ</p>
                        <div class="mbr-section-btn mt-3"><a class="btn btn-warning display-4"
                                                             href="https://mobiri.se/AnyLink1"><span
                                        class="mobi-mbri mobi-mbri-like mbr-iconfont mbr-iconfont-btn"></span>Ошый</a>
                            <a
                                    class="btn btn-warning display-4" href="https://mobiri.se/AnyLink1">2</a> <a
                                    class="btn btn-warning display-4" href="https://mobiri.se/secondEvent">Күчәргә</a>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-4">
                    <div class="image-wrapper">
                        <img src="https://s-vesti.ru/img/newsimages/1-1024x1024-5-w_1418f3da36f4.jpg" alt="error">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section data-bs-version="5.1" class="features15 cid-t3bcrpQ6Ng" id="features16-v">


    <div class="container">
        <div class="content-wrapper">
            <div class="row align-items-center">
                <div class="col-12 col-lg">
                    <div class="text-wrapper">
                        <h6 class="card-title mbr-fonts-style display-2"><strong>Образовательная лаборатория «Sanak
                                lab»</strong></h6>
                        <p class="mbr-text mbr-fonts-style mb-4 display-4">Ляйсан Сабитова</p>
                        <div class="mbr-section-btn mt-3"><a class="btn btn-warning display-4"
                                                             href="https://mobiri.se/AnyLink1"><span
                                        class="mobi-mbri mobi-mbri-like mbr-iconfont mbr-iconfont-btn"></span>Ошый</a>
                            <a
                                    class="btn btn-warning display-4" href="https://mobiri.se/AnyLink1">11</a> <a
                                    class="btn btn-warning display-4" href="https://mobiri.se/thirdEvent">Күчәргә</a>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-lg-4">
                    <div class="image-wrapper">
                        <img src="https://sun9-67.userapi.com/impf/c639427/v639427858/3a4e0/LwBzxnSLK6U.jpg?size=1200x1305&quality=96&sign=e53f9409c2b38b317ea4e4af3dbbe2af&type=album" alt="error">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="display-7"
         style="padding: 0;align-items: center;justify-content: center;flex-wrap: wrap;    align-content: center;display: flex;position: relative;height: 4rem;">
    <a href="https://mobiri.se/2751238" style="flex: 1 1;height: 4rem;position: absolute;width: 100%;z-index: 1;"><img
                alt="" style="height: 4rem;"
                src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="></a>
    <p style="margin: 0;text-align: center;" class="display-7">Кока кола в бутылке &#8204;</p><a style="z-index:1"
                                                                                                 href="https://mobirise.com/html-builder.html">Free
        HTML Website Builder</a></section>
<script src="/templates/assets/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/templates/assets/smoothscroll/smooth-scroll.js"></script>
<script src="/templates/assets/ytplayer/index.js"></script>
<script src="/templates/assets/dropdown/js/navbar-dropdown.js"></script>
<script src="/templates/assets/theme/js/script.js"></script>
<script src="/chats.js"></script>


</body>
</html>
