<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="Mobirise v5.6.5, mobirise.com">
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:image:src" content="">
    <meta property="og:image" content="">
    <meta name="twitter:title" content="CurrentEvent1">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="shortcut icon" href="https://avatars.mds.yandex.net/get-images-cbir/1780765/YsrctO5AJ50pc5CFxhgIJw546/ocr" type="image/x-icon">
    <meta name="description" content="">


    <title>CurrentEvent1</title>
    <link rel="stylesheet" href="/templates/assets/web/assets/mobirise-icons2/mobirise2.css">
    <link rel="stylesheet" href="/templates/assets/web/assets/mobirise-icons/mobirise-icons.css">
    <link rel="stylesheet" href="/templates/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/templates/assets/bootstrap/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="/templates/assets/bootstrap/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="/templates/assets/dropdown/css/style.css">
    <link rel="stylesheet" href="/templates/assets/socicon/css/styles.css">
    <link rel="stylesheet" href="/templates/assets/theme/css/style.css">
    <link rel="preload"
          href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"
          as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap">
    </noscript>
    <link rel="preload" as="style" href="/templates/assets/mobirise/css/mbr-additional.css">
    <link rel="stylesheet" href="/templates/assets/mobirise/css/mbr-additional.css" type="text/css">


</head>
<body>

<section data-bs-version="5.1" class="menu cid-s48OLK6784" once="menu" id="menu1-1j">

    <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
        <div class="container-fluid">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="https://mobiri.se">
                        <img src="https://avatars.mds.yandex.net/get-images-cbir/1780765/YsrctO5AJ50pc5CFxhgIJw546/ocr"
                             alt="Mobirise Website Builder" style="height: 3.9rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-black display-7"
                                                     href="https://mobiri.se">TatCenter</a></span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse"
                    data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true">
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4"
                                            href="https://mobirise.com/profileLink">Профиль</a></li>
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4"
                                            href="https://mobirise.com/serviceLink">Сервислар</a></li>
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4"
                                            href="https://mobirise.com/eventsLink">Чаралар</a></li>
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4"
                                            href="https://mobirise.com/cultureLink">Мәдәният</a></li>
                </ul>


            </div>
        </div>
    </nav>

</section>

<section data-bs-version="5.1" class="features1 cid-t3bujl0sSP" id="features2-1m">


    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-md-6 col-lg-3">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <a href="https://mobirise.com/LinkToIntellect"><span
                                class="mbr-iconfont mobi-mbri-idea mobi-mbri"></span></a>
                        <h4 class="card-title align-center mbr-black mbr-fonts-style display-7"><strong>Интеллектуаль
                            чаралар</strong></h4>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <span class="mbr-iconfont mobi-mbri-new-file mobi-mbri"
                              style="color: rgb(255, 255, 255); fill: rgb(255, 255, 255);"></span>
                        <h4 class="card-title align-center mbr-black mbr-fonts-style display-7"></h4>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <a href="https://mobirise.com/LinkToIntellect"><span
                                class="mbr-iconfont mobi-mbri-idea mobi-mbri"
                                style="color: rgb(255, 255, 255); fill: rgb(255, 255, 255);"></span></a>
                        <h4 class="card-title align-center mbr-black mbr-fonts-style display-7"></h4>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <div class="card-wrapper">
                    <div class="card-box align-center">
                        <a href="https://mobirise.com/LinkToPostanovki"><span class="mbr-iconfont mbri-camera"
                                                                              style="color: rgb(255, 255, 255); fill: rgb(255, 255, 255);"></span></a>
                        <h4 class="card-title align-center mbr-black mbr-fonts-style display-7"></h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section data-bs-version="5.1" class="image2 cid-t3buuHsOCU" id="image2-1n">


    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-lg-6">
                <div class="image-wrapper">
                    <img src="/templates/assets/images/photo-2022-03-30-19-48-34-2-1256x942.jpg"
                         alt="Mobirise Website Builder">
                    <p class="mbr-description mbr-fonts-style mt-2 align-center display-4">
                        Image Description</p>
                </div>
            </div>
            <div class="col-12 col-lg">
                <div class="text-wrapper">
                    <h3 class="mbr-section-title mbr-fonts-style mb-3 display-5"><strong>Tatar.Бу Хакатон</strong></h3>
                    <p class="mbr-text mbr-fonts-style display-7">Мәктәп укучылары һәм студентлар, сезне татар теле һәм
                        мәдәнияте өчен инновацион IT-чишелешләр булдыру өчен чакырабыз.
                        <br>
                        <br>Катнашучылар:
                        <br>7-11 сыйныф укучылары, көллият студентлары, югары уку йортларының 1-5 курс студентлары.
                        <br>
                        <br>Роли:
                        <br>ПО, Data Science белгечләре, дизайнерлар, маркетологлар, менеджерлар, аналитиклар,
                        тәрҗемәчеләр һәм лингвистлар.
                        <br>
                        <br>Катнашу өчен топ-3 сәбәп:
                        <br>- Процепны прототипка тормышка ашыру мөмкинлеге;
                        <br>- Ябык инструментларга керү;
                        <br>- ТР Фәннәр академиясендә стажировка узу мөмкинлеге;
                        <br>
                        <br>Приз фонды:
                        <br>300 000 сум
                        <br>
                        <br>
                        <br>Үткәрү даталары:
                        <br>11 апрельгә кадәр - командалар җыю, гариза бирү;
                        <br>11 апрель - хакатон командаларын сайлау;
                        <br>12 апрель - хакатонда катнашучылар командаларын игълан итү;
                        <br>15-17 апрель - хакатон, проектларны яклау һәм җиңүчеләрне игълан итү («ИТ-парк», Казан
                        шәһәре)</p>
                </div>
            </div>
        </div>
    </div>
</section>

<section data-bs-version="5.1" class="map1 cid-t3bvviosRj" id="map1-1p">


    <div class="container">
        <div class="mbr-section-head mb-4">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2"><strong>Үткәрү урыны</strong></h3>

        </div>
        <div class="google-map">
            <iframe frameborder="0" style="border:0"
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2243.734192062885!2d49.13126646624206!3d55.780488230560735!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x415ead0888e2f61d%3A0xc2f8ec9a11c5e6b7!2z0JPQkNCjICLQotC10YXQvdC-0L_QsNGA0Log0LIg0YHRhNC10YDQtSDQstGL0YHQvtC60LjRhSDRgtC10YXQvdC-0LvQvtCz0LjQuSDCq9CY0KIt0L_QsNGA0LrCuyI!5e0!3m2!1sru!2sru!4v1650125332568!5m2!1sru!2sru"
                    allowfullscreen=""></iframe>
        </div>
    </div>
</section>
<section class="display-7"
         style="padding: 0;align-items: center;justify-content: center;flex-wrap: wrap;    align-content: center;display: flex;position: relative;height: 4rem;">
    <a href="https://mobiri.se/2751238" style="flex: 1 1;height: 4rem;position: absolute;width: 100%;z-index: 1;"><img
            alt="" style="height: 4rem;"
            src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="></a>
    <p style="margin: 0;text-align: center;" class="display-7">Кока кола в бутылке &#8204;</p><a style="z-index:1"
                                                                                                 href="https://mobirise.com/html-builder.html">HTML
    Website Maker</a></section>
<script src="/templates/assets/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/templates/assets/smoothscroll/smooth-scroll.js"></script>
<script src="/templates/assets/ytplayer/index.js"></script>
<script src="/templates/assets/dropdown/js/navbar-dropdown.js"></script>
<script src="/templates/assets/theme/js/script.js"></script>


</body>
</html>
