<!DOCTYPE html>
<html>
<head>
    <!-- Site made with Mobirise Website Builder v5.6.5, https://mobirise.com -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="Mobirise v5.6.5, mobirise.com">
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:image:src" content="">
    <meta property="og:image" content="">
    <meta name="twitter:title" content="Home">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="shortcut icon" href="https://avatars.mds.yandex.net/get-images-cbir/1780765/YsrctO5AJ50pc5CFxhgIJw546/ocr" type="image/x-icon">
    <meta name="description" content="">


    <title>Home</title>
    <link rel="stylesheet" href="/templates/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/templates/assets/bootstrap/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="/templates/assets/bootstrap/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="/templates/assets/dropdown/css/style.css">
    <link rel="stylesheet" href="/templates/assets/socicon/css/styles.css">
    <link rel="stylesheet" href="/templates/assets/theme/css/style.css">
    <link rel="preload"
          href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap"
          as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link rel="stylesheet"
              href="https://fonts.googleapis.com/css?family=Jost:100,200,300,400,500,600,700,800,900,100i,200i,300i,400i,500i,600i,700i,800i,900i&display=swap">
    </noscript>
    <link rel="preload" as="style" href="/templates/assets/mobirise/css/mbr-additional.css">
    <link rel="stylesheet" href="/templates/assets/mobirise/css/mbr-additional.css" type="text/css">


</head>
<body>

<section data-bs-version="5.1" class="menu cid-s48OLK6784" once="menu" id="menu1-h">

    <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
        <div class="container-fluid">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a href="https://mobiri.se">
                        <img src="https://avatars.mds.yandex.net/get-images-cbir/1780765/YsrctO5AJ50pc5CFxhgIJw546/ocr" alt="Mobirise Website Builder"
                             style="height: 3.9rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-black display-7"
                                                     href="https://mobiri.se">CenTat</a></span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-toggle="collapse"
                    data-target="#navbarSupportedContent" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown nav-right" data-app-modern-menu="true">
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4"
                                            href="/profile/me">Профиль</a></li>
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4"
                                            href="/services">Сервислар</a></li>
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4"
                                            href="/events">Чаралар</a></li>
                    <li class="nav-item"><a class="nav-link link text-black text-primary display-4"
                                            href="https://selet.biz/tat/">Мәдәният</a></li>
                </ul>
            </div>
        </div>
    </nav>

</section>

<section data-bs-version="5.1" class="testimonials1 cid-t3bxM3hIxu" id="testimonials1-1r">


    <div class="container">

        <div class="row align-items-center">
            <div class="col-12 col-md-4">
                <div class="image-wrapper">
                    <img src="https://sun9-81.userapi.com/impg/iXFuPbITSYDyls9ZWn1kntqkwf4-yoVCJIEO0Q/NeYq040lLoc.jpg?size=1440x2160&quality=96&sign=a818a391e09fe281fe6b7c1e52ef55ba&type=album" alt="Mobirise Website Builder">
                </div>
            </div>
            <div class="col-12 col-md">
                <div class="text-wrapper">
                    <p class="mbr-text mbr-fonts-style mb-4 display-7">фронт энд бэкэнд питон девелопер абузер машин
                        лернинг джуниор дук 19y.o.</p>
                    <p class="name mbr-fonts-style mb-1 display-4"><strong>Ziper Lin</strong></p>
                    <p class="position mbr-fonts-style display-4">Эшкәртүче/Оештыручы<br></p>
                </div>
            </div>
        </div>
    </div>
</section>

<section data-bs-version="5.1" class="info4 cid-t3bzt4XlCU" id="info4-1u">


    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <h3 class="mbr-section-title mbr-fonts-style display-5">
                    <strong>Ziper lin катнашты:</strong></h3>
                <p class="mbr-text mbr-fonts-style mb-4 display-5">Мәктәп укучылары һәм студентлар, сезне татар теле
                    өчен инновацион IT-чишелешләр булдыру өчен чакырабыз....</p>
                <div class="link-wrap">
                    <p class="link mbr-fonts-style mb-4 display-1"><a class="text-primary" href="#">Хакатон Татар Бу</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="display-7"
         style="padding: 0;align-items: center;justify-content: center;flex-wrap: wrap;    align-content: center;display: flex;position: relative;height: 4rem;">
    <a href="https://mobiri.se/2751238" style="flex: 1 1;height: 4rem;position: absolute;width: 100%;z-index: 1;"><img
                alt="" style="height: 4rem;"
                src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="></a>
    <p style="margin: 0;text-align: center;" class="display-7">Кока кола в стеклянной бутылке &#8204;</p><a style="z-index:1"
                                                                                                 href="https://mobirise.com/website-maker.html">Website
        Maker</a></section>
<script src="/templates/assets/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="/templates/assets/smoothscroll/smooth-scroll.js"></script>
<script src="/templates/assets/ytplayer/index.js"></script>
<script src="/templates/assets/dropdown/js/navbar-dropdown.js"></script>
<script src="/templates/assets/theme/js/script.js"></script>


</body>
</html>
